name: CI
on: push
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "14"
      - name: Install
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install
      - name: Test
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: test
      - name: Build
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: build
      - name: Release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
